### ISSUE TITLE
Default Prometheus port

### ISSUE THREAD

**Issue by miton18** [CleverCloud/documentation#1]
From what I see, the default Prometheus port configured in Telegraf is 9100 and not 8080 like it's said in the docs

**Comment by Sykursen** [comment]
Already fix.

Issue to to be closed

**Comment by miton18** [comment]
this is not fixed 
https://developers.clever-cloud.com/doc/reference/reference-environment-variables/#configure-extra-software

**Comment by davlgd** [comment]
It is now ;)
