### ISSUE TITLE
Support Yarn 3

### ISSUE THREAD

**Issue by alexislefebvre** [CleverCloud/documentation#12]
Yarn 3 was released in 2021: https://github.com/yarnpkg/berry/releases/tag/%40yarnpkg%2Fcli%2F3.0.0

Yet the documentation only explain how to use Yarn 1 and 2: https://www.clever-cloud.com/doc/getting-started/by-language/node/#supported-package-managers

**Comment by juliamrch** [comment]
That's because there is no support for Yarn 3 yet (althought you can install it on the VM)

**Comment by alexislefebvre** [comment]
Well, Yarn 4 as been released since I opened this ticket, yet Clever Cloud only supports only versions 1 and 2.

Is there a place to ask Clever Cloud to support more versions of some popular libraries?
