### ISSUE TITLE
fix: update Hextra to get canonical URLs

### ISSUE THREAD

**Issue by davlgd** [CleverCloud/documentation#158]
### Checking for existing issue

- [X] I have checked for existing [issues](https://github.com/CleverCloud/documentation/issues)

### Describe the content you'd like to see

The current documentation don't have canonical URLs in its `<head>` section. It's because it wasn't included in Hextra theme we use. As [it's now included](https://github.com/imfing/hextra/pull/261) in the theme we should watch for next version and update when available.

**Comment by cnivolle** [comment]
Yup, I might get get integrated in the next release (7.0.2?) of Hextra. 
We're watching this.

**Comment by davlgd** [comment]
7.0.2 is available with the fix: 
https://github.com/imfing/hextra/releases/tag/v0.7.2
