### ISSUE TITLE
Fix addon api doc

### ISSUE THREAD

**Issue by vballu** [CleverCloud/documentation#18]
https://github.com/CleverCloud/doc.clever-cloud.com/blob/master/extend/add-ons-api.md

This doc is outdated and must be fix

**Comment by cnivolle** [comment]
@vballu do you have any insights on how we can contribute ?

**Comment by vballu** [comment]
@cnivolle I have to deep dive into this doc to highlight outdated points and fix it. I have it in my to do !

I'll try to do that this week

**Comment by davlgd** [comment]
Fixed by #303
