### ISSUE TITLE
fix: change <ul> margin

### ISSUE THREAD

**Issue by davlgd** [CleverCloud/documentation#183]
### Checking for existing issue

- [X] I have checked for existing [issues](https://github.com/CleverCloud/documentation/issues)

### Describe the content you'd like to see

If I use a 2-levels list, the `<ul>` margin leads to render issue. As you can see below, `margin-top` is too high and there is no `margin-bottom`:

<img width="796" alt="image" src="https://github.com/CleverCloud/documentation/assets/1110600/bb08f448-cba8-4305-bc99-e91514caaff4">

If I replace `margin-top: 1.5em` by `margin-bottom: 1.5em` result seems better:

<img width="796" alt="image" src="https://github.com/CleverCloud/documentation/assets/1110600/59a6b48d-60c8-4579-8107-f4834b921742">

**Comment by davlgd** [comment]
Maybe fixed by Hextra 7.0.2: 
https://github.com/imfing/hextra/releases/tag/v0.7.2

> fix: set top margin to zero for nested list by @imfing in https://github.com/imfing/hextra/pull/276

**Comment by davlgd** [comment]
Maybe fixed by Hextra 0.7.2:
https://github.com/imfing/hextra/releases/tag/v0.7.2

> fix: set top margin to zero for nested list by @imfing in https://github.com/imfing/hextra/pull/276

**Comment by juliamrch** [comment]
> I've quickly checked, it's not enough. I'll open an issue in Hextra repository. I let you decide if you want to make a local fix or wait for a next release on this

Nice catch. Maybe we could summit a PR on Hextra repo if we fix it before Xin does. @imfing you in?

**Comment by imfing** [comment]
> > I've quickly checked, it's not enough. I'll open an issue in Hextra repository. I let you decide if you want to make a local fix or wait for a next release on this
> 
> 
> 
> Nice catch. Maybe we could submit a PR on Hextra repo if we fix it before Xin does. @imfing you in? 

Yes please 🙌

**Comment by imfing** [comment]
should be fixed in https://github.com/imfing/hextra/pull/280
