### ISSUE TITLE
Doc:  NodeJS "latest version" sould be more explicit

### ISSUE THREAD

**Issue by Dekabry** [CleverCloud/documentation#292]
### Checking for existing issue

- [X] I have checked for existing [issues](https://github.com/CleverCloud/documentation/issues)

### **Issue**
"We will use the latest TLS version" is misleading: it's not the latest version, it's the latest version Clever Cloud **offers**.
Customer thought they could use the latest NodeJS version, but we are still a few versions behind.

### **Where**
[Here](https://developers.clever-cloud.com/doc/applications/javascript/nodejs/#set-nodejs-version)

### **Proposed fix**
Append this section by mentionning it's the latest version available **on Clever Cloud**.

**Comment by juliamrch** [comment]
Good catch, do you want to take this one?

**Comment by Dekabry** [comment]
I'll see for that ! (didn't notice your answer :< )
