### ISSUE TITLE
Doc: accesslogs from CLI do not have "--follow" as argument anymore

### ISSUE THREAD

**Issue by Dekabry** [CleverCloud/documentation#322]
### Checking for existing issue

- [X] I have checked for existing [issues](https://github.com/CleverCloud/documentation/issues)

### Issue
The Clever CLI page for log management mention we can use `--follow` argument to continuously display logs.
This argument doesn't exist anymore, the `--follow` argument is now the default behavior.  

### Where
[Here](https://developers.clever-cloud.com/doc/administrate/log-management/#access-logs)
_"As with the logs command, you can specify --before and --after flags **as well as the --follow to display access logs continuously**'_

### Proposed fix
Delete the mention of the `--follow` argument. 
Mention the logs will continuously be followed by default.

**Comment by Kirbeerus** [comment]
Resolved by 8803771
