### ISSUE TITLE
Workflow example for Github & Gitlab

### ISSUE THREAD

**Issue by gaelreyrol** [CleverCloud/documentation#34]
I think we should demonstrate how to deploy from Github and Gitlab CI ! 
As well as showing how to create preview-apps.

Here is a well crafted example of Github CI workflow for deployment and preview apps: https://github.com/betagouv/itou/tree/master/.github/workflows

**Comment by juliamrch** [comment]
It's published here now: https://developers.clever-cloud.com/doc/ci-cd/
