### ISSUE TITLE
Doc: create a guide showing how to host a static website using Cellar + Hugo

### ISSUE THREAD

**Issue by Dekabry** [CleverCloud/documentation#348]
### Checking for existing issue

- [X] I have checked for existing [issues](https://github.com/CleverCloud/documentation/issues)

### Describe the content you'd like to see

Create a guide showing how to host a static website made with Hugo, using Cellar.

**Comment by Kirbeerus** [comment]
@Dekabry It seems like you already added the guide for hosting a static website using Cellar + Hugo to the Doc.
Maybe we can close this issue?

**Comment by Kirbeerus** [comment]
Resolved by 562e9cd
