### ISSUE TITLE
CSS problems with some sections/blocks in dark mode

### ISSUE THREAD

**Issue by davlgd** [CleverCloud/documentation#355]
### Checking for existing issue

- [X] I have checked for existing [issues](https://github.com/CleverCloud/documentation/issues)

### Describe the content you'd like to see

It seems there are CSS troubles with dark mode with some blocks, such as this one in `postmortem`:

[image](https://github.com/user-attachments/assets/103a8b88-d503-48aa-abf6-3805072b0691)

Or this one at the bottom of the documentation home:

<img width="1179" alt="image" src="https://github.com/user-attachments/assets/bf660b1f-9cac-476f-b691-25b48eaf8d97">

**Comment by juliamrch** [comment]
fixed on commit `90410936`
