### ISSUE TITLE
[JAVA-WAR] Update table of server containers to reflect if they are EOL or not

### ISSUE THREAD

**Issue by juliamrch** [CleverCloud/documentation#390]
The table of server containers should be updated to reflect if they are EOL or not.  I flagged the Jetty ones, but you'll have to address the other containers.

Any container no longer being supported by the maintainers should not be used on the open internet as it does not contain fixes for behaviors that the industry as a whole have adopted. (eg: TLS changes, Cookie changes, HTTP/1.x spec changes, Browser changes, etc)

If you insist on keeping these EOL container versions listed in your documentation, then list them as EOL (should not be used anymore, upgrade to a supported version as soon as possible)

_Originally posted by @joakime in https://github.com/CleverCloud/documentation/issues/387#issuecomment-2388850844_

**Comment by cnivolle** [comment]
fixed by #387
