### ISSUE TITLE
Don't publish the partials

### ISSUE THREAD

**Issue by alexislefebvre** [CleverCloud/documentation#4]
Searching "CC_CACHE_DEPENDENCIES" through a search engine gives this as the first result: https://www.clever-cloud.com/doc/partials/cached-dependencies/

It looks like this text is meant to be included in other pages, like here: https://www.clever-cloud.com/doc/partials/language-specific-deploy/haskell/#cached-dependencies

I suggest to remove the partials from the online documentation so that the search engines remove them from their index.

**Comment by juliamrch** [comment]
This has been solved in V2, partials have been removed from the `/content` directory ✌️
