### ISSUE TITLE
Variables linked to versions files

### ISSUE THREAD

**Issue by juliamrch** [CleverCloud/documentation#427]
Maybe we can link to the automated part of PHP doc to avoid duplicate and misalignment? https://developers.clever-cloud.com/doc/applications/php/#choose-your-php-version

_Originally posted by @davlgd in https://github.com/CleverCloud/documentation/pull/416#discussion_r1831101035_

**Comment by cnivolle** [comment]
Resolved by 04ed162b057c208c3cecf4507cdfc6926f6c494c
