### ISSUE TITLE
Laravel: use of "optional" term in titles and wrong titles levels

### ISSUE THREAD

**Issue by BlackYoup** [CleverCloud/documentation#59]
It seems that we use the "optional" term in some titles in the Laravel documentation. It doesn't seem we do that in other pages. Instead we use a regular title and then start the sentence with "if you need XXX then YYY". Do we want to keep this?

Also, titles are not using the right markdown levels. There are no table of contents probably because of it https://www.clever-cloud.com/doc/php/tutorial-laravel/

**Comment by juliamrch** [comment]
Laravel tutorial has been revamped this way: https://developers.clever-cloud.com/guides/tutorial-laravel/

Optional configuration means it's not necessary for the app to deploy and run, I guess. 

But I see that an internal redirection is needed for the previous link, will fix this asap.
