### ISSUE TITLE
Add support for tags

### ISSUE THREAD

**Issue by divarvel** [CleverCloud/documentation#75]
Applications and addons can have tags 
https://www.clever-cloud.com/doc/api/#!/addons/getOrganisationsIdAddonsAddonIdTags
https://www.clever-cloud.com/doc/api/#!/applications/getOrganisationsIdApplicationsAppIdTags

For now it's not used in the console, but it can allow users to group things even though it's for api users only.

**Comment by davlgd** [comment]
It will be documented when implemented in Console or CLI
