### ISSUE TITLE
New page with details regarding Github app creation

### ISSUE THREAD

**Issue by urcadox** [CleverCloud/documentation#79]
The API documentation is lacking in this regard and it's hard to be exhaustive and understandable on this subject. Particularly when there will be more integrations.

In the mean time, here is an example of what the `oauthApp` field in the `POST ../applications` request body should be if you want to create a Github app (the field is renamed to `githubApp`):

```json
{
  "githubApp": {
    "id": "42056606",
    "owner": "CleverCloud",
    "name": "demo-nodejs-mongodb",
    "description": "NodeJS and mongodb example application",
    "gitUrl": "https://github.com/CleverCloud/demo-nodejs-mongodb.git",
    "priv": false
  }
}
```

**Comment by juliamrch** [comment]
Not sure this very old issue is still relevant.
